rename_list = [
    ('l', 'language'),
    ('QA', 'gender'),
    ('QB', 'age'),
    ('QC', 'province'),
    ('QD_1', 'license_mutualfunds'),
    ('QD_2', 'license_insurance'),
    ('QD_3', 'license_securities'),
    ('Q1', 'educ'),
    ('Q2', 'marital_status'),
    ('Q3', 'children'),
    ('Q12', 'employment'),
    ('Q13_1', 'certification_qafp'),
    ('Q13_2', 'certification_cfp'),
    ('Q13_3', 'certification_plfin'),
    ('Q13_7777777', 'certification_dk'),
    ('Q13_8888888', 'certification_pnts'),
    ('Q14_1', 'certification_cim'),
    ('Q14_2', 'certification_cfa'),
    ('Q14_3', 'certification_clu'),
    ('Q14_4', 'certification_cpa'),
    ('Q14_5', 'certification_tep'),
    ('Q14_6', 'certification_pfp'),
    ('Q14_7', 'certification_rfp'),
    ('Q14_8', 'certification_rrc'),
    ('Q14_9', 'certification_chs'),
    ('Q14_10', 'certification_cpfintl'),
    ('Q14_11', 'certification_epc'),
    ('Q14_12', 'certification_other'),
    ('Q15_1', 'license_prod_ul'),
    ('Q15_2', 'license_prod_mf'),
    ('Q15_3', 'license_prod_segfund'),
    ('Q15_4', 'license_prod_annuities'),
    ('Q15_5', 'license_prod_ltci'),
    ('Q15_6', 'license_prod_ilgic'),
    ('Q15_7', 'license_prod_etf'),
    ('Q16', 'work_experience'),
    ('Q17', 'service'),
    ('Q18', 'compensation'),
    ('hQ18_1', 'comp_salaryonly'),
    ('hQ18_2', 'comp_salarybonus'),
    ('hQ18_3', 'comp_commissions'),
    ('hQ18_4', 'comp_aum'),
    ('hQ18_5', 'comp_ffa'),
    ('hQ18_6', 'comp_other'),
    ('Q19', 'refer'),
    ('Q20', 'patience'),
    ('Q21', 'risk'),
    ('Q22_1', 'emo_extra_enthu'),
    ('Q22_2', 'emo_criti_quarrel'),
    ('Q22_3', 'emo_depend_selfdis'),
    ('Q22_4', 'emo_anxious_upset'),
    ('Q22_5', 'emo_open_complex'),
    ('Q22_6', 'emo_reser_quiet'),
    ('Q22_7', 'emo_sympa_warm'),
    ('Q22_8', 'emo_disorg_careless'),
    ('Q22_9', 'emo_calm_stable'),
    ('Q22_10', 'emo_convent_uncreative'),
    ('Q23_1', 'state_bequest'),
    ('Q23_2', 'state_inherithome'),
    ('Q23_3', 'state_sellhome'),
    ('Q23_4', 'state_debtnogood'),
    ('Q23_5', 'state_qualitylife'),
    ('Q23_6', 'state_investshares'),
    ('Q23_7', 'state_optimfinpl'),
    ('Q25_1', 'fparea_ag'),
    ('Q25_2', 'fparea_credit'),
    ('Q25_3', 'fparea_intl'),
    ('Q25_4', 'fparea_divorce'),
    ('Q25_5', 'fparea_educ'),
    ('Q25_6', 'fparea_groupben'),
    ('Q25_7', 'fparea_estate'),
    ('Q25_8', 'fparea_execomp'),
    ('Q25_9', 'fparea_insur'),
    ('Q25_10', 'fparea_invest'),
    ('Q25_11', 'fparea_mortgage'),
    ('Q25_12', 'fparea_disabil'),
    ('Q25_13', 'fparea_privbank'),
    ('Q25_14', 'fparea_respinvest'),
    ('Q25_15', 'fparea_retplan'),
    ('Q25_16', 'fparea_smallbus'),
    ('Q25_17', 'fparea_succplan'),
    ('Q25_18', 'fparea_taxplan'),
    ('Q26_1', 'prod_own_ul'),
    ('Q26_2', 'prod_own_mf'),
    ('Q26_3', 'prod_own_segfund'),
    ('Q26_4', 'prod_own_annuities'),
    ('Q26_5', 'prod_own_ltci'),
    ('Q26_6', 'prod_own_ilgic'),
    ('Q26_7', 'prod_own_etf'),
    ('Q26_8', 'prod_own_realestate'),
    ('Q27', 'value_realestate'),
    ('Q27dk_9999999', 'value_realestate_dkpnts'),
    ('Q28_1', 'prod_spouse_ul'),
    ('Q28_2', 'prod_spouse_mf'),
    ('Q28_3', 'prod_spouse_segfund'),
    ('Q28_4', 'prod_spouse_annuities'),
    ('Q28_5', 'prod_spouse_ltci'),
    ('Q28_6', 'prod_spouse_ilgic'),
    ('Q28_7', 'prod_spouse_etf'),
    ('Q28_8', 'prod_spouse_realestate'),
    ('Q29', 'db_plan'),
    ('Q30x1_1', 'rrsp_own'),
    ('Q30x2_1', 'rrsp_balance'),
    ('Q30x3_1', 'rrsp_share'),
    ('Q30x1_2', 'tfsa_own'),
    ('Q30x2_2', 'tfsa_balance'),
    ('Q30x3_2', 'tfsa_share'),
    ('Q30x1_3', 'grouplan_own'),
    ('Q30x2_3', 'grouplan_balance'),
    ('Q30x3_3', 'grouplan_share'),
    ('Q30x1_4', 'dcplan_own'),
    ('Q30x2_4', 'dcplan_balance'),
    ('Q30x3_4', 'dcplan_share'),
    ('Q30x1_5', 'otheracc_own'),
    ('Q30x2_5', 'otheracc_balance'),
    ('Q30x3_5', 'otheracc_share'),
    ('Q30x1_9999999', 'accounts_pnts'),
    ('Q32', 'stockmkt_expectation'),
    ('Q33', 'stockmkt_confidence'),
    ('Q34_1', 'stockmkt_40p'),
    ('Q34_2', 'stockmkt_30_40'),
    ('Q34_3', 'stockmkt_20_30'),
    ('Q34_4', 'stockmkt_10_20'),
    ('Q34_5', 'stockmkt_0_10'),
    ('Q34_6', 'stockmkt_m10_0'),
    ('Q34_7', 'stockmkt_m20_m10'),
    ('Q34_8', 'stockmkt_m30_m20'),
    ('Q34_9', 'stockmkt_m40_m30'),
    ('Q34_10', 'stockmkt_m40p'),
    ('Q35', 'selfass'),
    ('Q36', 'selfconf'),
    ('Q39', 'credits'),
    ('NAMExS_1', 'scn1a_name'),
    ('APR_1', 'scn1a_apr'),
    ('MTR_1', 'scn1a_mtr'),
    ('SOLICITxS_1', 'scn1a_solicit'),
    ('Q4', 'scn1a_answer'),
    ('NAMExS_2', 'scn1b_name'),
    ('APR_2', 'scn1b_apr'),
    ('MTR_2', 'scn1b_mtr'),
    ('SOLICITxS_2', 'scn1b_solicit'),
    ('Q5', 'scn1b_answer'),
    ('NAMExL_1', 'scn2a_name'),
    ('BEQUESTxL_1', 'scn2a_bequest'),
    ('RATExL_1', 'scn2a_rate'),
    ('HEALTHxL_1', 'scn2a_health'),
    ('SOLICITxL_1', 'scn2a_solicit'),
    ('PAYOUT_1', 'scn2a_payout'),
    ('COMP_1', 'scn2a_comp'),
    ('Q6', 'scn2a_answer'),
    ('NAMExL_2', 'scn2b_name'),
    ('BEQUESTxL_2', 'scn2b_bequest'),
    ('RATExL_2', 'scn2b_rate'),
    ('HEALTHxL_2', 'scn2b_health'),
    ('SOLICITxL_2', 'scn2b_solicit'),
    ('PAYOUT_2', 'scn2b_payout'),
    ('COMP_2', 'scn2b_comp'),
    ('Q7', 'scn2b_answer'),
    ('NAMExL_1', 'scn2a_name'),
    ('NAMExC_1', 'scn3a_name'),
    ('BORROW_1', 'scn3a_borrow'),
    ('HEALTHxC_1', 'scn3a_health'),
    ('RATExC_1', 'scn3a_rate'),
    ('SOLICITxC_1', 'scn3a_solicit'),
    ('Q8', 'scn3a_answer'),
    ('NAMExC_2', 'scn3b_name'),
    ('BORROW_2', 'scn3b_borrow'),
    ('HEALTHxC_2', 'scn3b_health'),
    ('RATExC_2', 'scn3b_rate'),
    ('SOLICITxC_2', 'scn3b_solicit'),
    ('Q9', 'scn3b_answer'),
    ('NAMExI_1', 'scn4a_name'),
    ('MUTFEES_1', 'scn4a_mutfees'),
    ('SEGFEES_1', 'scn4a_segfees'),
    ('SOLICITxI_1', 'scn4a_solicit'),
    ('Q10', 'scn4a_answer'),
    ('NAMExI_2', 'scn4b_name'),
    ('MUTFEES_2', 'scn4b_mutfees'),
    ('SEGFEES_2', 'scn4b_segfees'),
    ('SOLICITxI_2', 'scn4b_solicit'),
    ('Q11', 'scn4b_answer'),
    ('Q24', 'income'),
    ('Q24dk_9999999', 'income_dk_pnts'),
    ('Q24a', 'income_gt60k'),
    ('Q24b', 'income_lt160k'),
    ('Q24c', 'income_gt90k'),
    ('Q24d', 'income_lt30k'),
    ('hQ31Num1', 'debt_thresh1'),
    ('hQ31Num2', 'debt_thresh2'),
    ('Q31', 'debt'),
    ('Q31dk_9999999', 'debt_dk_pnts'),
    ('Q31a', 'debt_gt1'),
    ('Q31b', 'debt_lt2')
]


variable_labels = {
    'language': "Please select your preferred language",
    'gender': "What is your gender?",
    'age': "Age",
    'province': "Which province or territory do you live in?",
    'license_mutualfunds': "License to sell mutual funds",
    'license_insurance': "License to sell insurance",
    'license_securities': "License to sell securities",
    'educ': "What is the highest level of education you have reached?",
    'marital_status': "What is your marital status?",
    'children': "Do you have children?",
    'employment': "What best describes your place of employment?",
    'certification_qafp': "QAFP",
    'certification_cfp': "CFP",
    'certification_plfin': "Pl. Fin.",
    'certification_dk': "Don't know",
    'certification_pnts': "Prefer not to say",
    'certification_cim': "Chartered Investment Manager (CIM)",
    'certification_cfa': "Chartered Financial Analyst (CFA)",
    'certification_clu': "Chartered Life Underwriter (CLU)",
    'certification_cpa': "Chartered Professional Accountant (CPA)",
    'certification_tep': "Trust and Estate Practitioner (TEP)",
    'certification_pfp': "Personal Financial Planner (PFP)",
    'certification_rfp': "Registered Financial Planner (R.F.P.)",
    'certification_rrc': "Registered Retirement Consultant (RRC)",
    'certification_chs': "Certified Health Insurance Specialist (CHS)",
    'certification_cpfintl': "Certified Financial Planner (Other Country)",
    'certification_epc': "Elder Planning Counselor (EPC)",
    'certification_other': "Other",
    'license_prod_ul': "Universal life insurance",
    'license_prod_mf': "Mutual funds",
    'license_prod_segfund': "Segregated funds",
    'license_prod_annuities': "Annuities",
    'license_prod_ltci': "Long-term care insurance",
    'license_prod_ilgic': "Index-linked GIC",
    'license_prod_etf': "Exchange-traded funds",
    'work_experience': "Work experience (years)",
    'service': "Which services do you predominantly provide as a financial planner?",
    'compensation': "How are you primarily compensated for your services as a financial planner?",
    'comp_salaryonly': "Salary only",
    'comp_salarybonus': "Salary plus bonus based on sales",
    'comp_commissions': "Primarily commissions",
    'comp_aum': "Primarily Assets under Management",
    'comp_ffa': "Primarily fee for advice",
    'comp_other': "Other",
    'refer': "Consult with or refer clients to other experts",
    'patience': "Patience in financial decisions",
    'risk': "Amount of financial risk willing to take in investments",
    'emo_extra_enthu': "Extraverted, enthusiastic",
    'emo_criti_quarrel': "Critical, quarrelsome",
    'emo_depend_selfdis': "Dependable, self-disciplined",
    'emo_anxious_upset': "Anxious, easily upset",
    'emo_open_complex': "Open to new experiences, complex",
    'emo_reser_quiet': "Reserved, quiet",
    'emo_sympa_warm': "Sympathetic, warm",
    'emo_disorg_careless': "Disorganized, careless",
    'emo_calm_stable': "Calm, emotionally stable",
    'emo_convent_uncreative': "Conventional, uncreative",
    'state_bequest': "Parents should set aside money for children once they die",
    'state_inherithome': "Children should inherit their parents' family home",
    'state_sellhome': "A house should only be sold in case of financial hardship",
    'state_debtnogood': "Being in debt is never a good thing",
    'state_qualitylife': "I prefer to live well but for fewer years",
    'state_investshares': "Not investing in shares is a huge mistake for investors",
    'state_optimfinpl': "Clients have a good idea of optimal financial strategies",
    'fparea_ag': "Agriculture / farm business planning",
    'fparea_credit': "Credit counselling and bankruptcy",
    'fparea_intl': "Cross-border and international planning",
    'fparea_divorce': "Divorce and separation planning",
    'fparea_educ': "Education planning",
    'fparea_groupben': "Employee / Group benefit plans",
    'fparea_estate': "Estate planning",
    'fparea_execomp': "Executive compensation and benefits",
    'fparea_insur': "Insurance planning",
    'fparea_invest': "Investment planning",
    'fparea_mortgage': "Mortgages and debt planning",
    'fparea_disabil': "Planning for those with disabilities",
    'fparea_privbank': "Private banking",
    'fparea_respinvest': "Responsible investing",
    'fparea_retplan': "Retirement planning",
    'fparea_smallbus': "Small business planning",
    'fparea_succplan': "Succession planning",
    'fparea_taxplan': "Tax planning",
    'prod_own_ul': "Universal life insurance",
    'prod_own_mf': "Mutual funds",
    'prod_own_segfund': "Segregated funds",
    'prod_own_annuities': "Annuity",
    'prod_own_ltci': "Long-term care insurance",
    'prod_own_ilgic': "Index-linked GIC",
    'prod_own_etf': "Exchange-traded funds",
    'prod_own_realestate': "Real estate",
    'value_realestate': "Please provide your best estimate of the current value of any real estate you own",
    'value_realestate_dkpnts': "D/k pnts Real estate value",
    'prod_spouse_ul': "Universal life insurance",
    'prod_spouse_mf': "Mutual funds",
    'prod_spouse_segfund': "Segregated funds",
    'prod_spouse_annuities': "Annuity",
    'prod_spouse_ltci': "Long-term care insurance",
    'prod_spouse_ilgic': "Index-linked GIC",
    'prod_spouse_etf': "Exchange-traded funds",
    'prod_spouse_realestate': "Real estate",
    'db_plan': "Do you currently participate in a Defined Benefit (DB) pension plan offered by your employer?",
    'rrsp_own': "Share own RRSPs",
    'rrsp_balance': "RRSPs (Account balance)",
    'rrsp_share': "RRSPs (Risky Share)",
    'tfsa_own': "Share own TFSAs",
    'tfsa_balance': "TFSAs (Account balance)",
    'tfsa_share': "TFSAs (Risky Share)",
    'grouplan_own': "Share own group plans",
    'grouplan_balance': "Group plans (Account balance)",
    'grouplan_share': "Group plans (Risky Share)",
    'dcplan_own': "Share own DC plan",
    'dcplan_balance': "DC plan (Account balance)",
    'dcplan_share': "DC plan (Risky Share)",
    'otheracc_own': "Share own other accounts",
    'otheracc_balance': "Other accounts (Account balance)",
    'otheracc_share': "Other accounts (Risky Share)",
    'accounts_pnts': "Don't know or prefer not to say (accounts)",
    'stockmkt_expectation': "Expected return of Canadian stock market",
    'stockmkt_confidence': "How confident are you about your response to the stock market expectation?",
    'stockmkt_40p': "More than 40%",
    'stockmkt_30_40': "Between 30% and 40%",
    'stockmkt_20_30': "Between 20% and 30%",
    'stockmkt_10_20': "Between 10% and 20%",
    'stockmkt_0_10': "Between 0% and 10%",
    'stockmkt_m10_0': "Between -10% and 0%",
    'stockmkt_m20_m10': "Between -20% and -10%",
    'stockmkt_m30_m20': "Between -30% and -20%",
    'stockmkt_m40_m30': "Between -40% and -30%",
    'stockmkt_m40p': "Less than -40%",
    'selfass': "Please indicate how you would assess your own financial advice compared to other financial planners.",
    'selfconf': "When considering your own investments in the next three months, do you have confidence in beating the market as a whole?",
    'credits': "(Missing) Please indicate whether you wish to obtain 0.5 continuing education credit.",
    'scn1a_name': "Name",
    'scn1a_apr': "APR",
    'scn1a_mtr': "MTR",
    'scn1a_solicit': "Prompt",
    'scn1a_answer': "Savings vignette",
    'scn1b_name': "Name",
    'scn1b_apr': "APR",
    'scn1b_mtr': "MTR",
    'scn1b_solicit': "Prompt",
    'scn1b_answer': "Savings vignette",
    'scn2a_name': "Name",
    'scn2a_bequest': "Bequest",
    'scn2a_rate': "Rate",
    'scn2a_health': "Health",
    'scn2a_payout': "Payout",
    'scn2a_comp': "Compensation promt",
    'scn2a_solicit': "Product prompt",
    'scn2a_answer': "Decumulation vignette",
    'scn2b_name': "Name",
    'scn2b_bequest': "Bequest",
    'scn2b_rate': "Rate",
    'scn2b_health': "Health",
    'scn2b_payout': "Payout",
    'scn2b_comp': "Compensation promt",
    'scn2b_solicit': "Product prompt",
    'scn2b_answer': "Decumulation vignette",
    'scn3a_name': "Name",
    'scn3a_borrow': "Borrow",
    'scn3a_health': "Health",
    'scn3a_rate': "Rate",
    'scn3a_solicit': "Prompt",
    'scn3a_answer': "Long-term care vignette",
    'scn3b_name': "Name",
    'scn3b_borrow': "Borrow",
    'scn3b_health': "Health",
    'scn3b_rate': "Rate",
    'scn3b_solicit': "Prompt",
    'scn3b_answer': "Long-term care vignette",
    'scn4a_name': "Name",
    'scn4a_mutfees': "mutfees4",
    'scn4a_segfees': "segfees4",
    'scn4a_solicit': "Prompt",
    'scn4a_answer': "Investment vignette",
    'scn4b_name': "Name",
    'scn4b_mutfees': "mutfees4",
    'scn4b_segfees': "segfees4",
    'scn4b_solicit': "Prompt",
    'scn4b_answer': "Investment vignette",
    'income': "Best estimate of personal income for 2020 (all sources, before taxes and deductions (but net of business or self-employment expenses)",
    'income_dk_pnts': "Income D/k or pnts",
    'income_gt60k': "Income - Is it more than $60,000?",
    'income_lt160k': "Income - Is it less than $160,000?",
    'income_gt90k': "Income - Is it more than $90,000?",
    'income_lt30k': "Income - Is it more than $30,000?",
    'debt': "Best estimate of any outstanding debt that you have.",
    'debt_dk_pnts': "Debt D/k or pnts",
    'debt_gt1': "Debt - Is it more than debt_thresh1",
    'debt_lt2': "Debt - Is it less than debt_thresh2",
    'reminder': "Complete after reminder",
    'female': "Female",
    'french': "French survey",
    'married': "Married or Common-law",
    'child': "Has children",
    'educ_hs_less': "High school or less",
    'educ_some_uni': "College or some university",
    'educ_bach_more': "Bachelor degree or more",
    'qc': "Quebec",
    'ont': "Ontario",
    'bc': "BC",
    'alberta': "Alberta",
    'other_prov': "Other province",
    'other': "Other",
    'income_impute_t': "Annual income (imputed)('000$)", 
    'income_t': "Annual income ('000$)", 
    'debt_impute_t': "Debt (imputed)('000$)", 
    'debt_t': "Debt ('000$)",
    'value_realestate_t': "Value of real estate ('000 $)",
    'db_plan_ds': "Has DB plan",
    'rrsp_own_ds': "RRSPs (Ownership)", 
    'rrsp_balance_t': "Amount in RRSP ('000 $)", 
    'rrsp_risky': "RRSP half or more is risky",
    'tfsa_own_ds': "TFSAs (Ownership)", 
    'tfsa_balance_t': "Amount in TFSA ('000 $)", 
    'tfsa_risky': "TFSA half or more is risky",
    'grouplan_own_ds': "Group plans (Ownership)", 
    'grouplan_balance_t': "Amount in group plan ('000 $)", 
    'grouplan_risky': "Group plan half or more is risky",
    'dcplan_own_ds': "DC plan (Ownership)", 
    'dcplan_balance_t': "Amount in DC plan ('000 $)", 
    'dcplan_risky': "DC plan half or more is risky",
    'otheracc_own_ds': "Other accounts (Ownership)", 
    'otheracc_balance_t': "Amount in other accounts ('000 $)", 
    'otheracc_risky': "Other accounts half or more is risky",
    'iqpf': "IQPF",
    'fparea_educ_ds': "Education planning", 
    'fparea_estate_ds': "Estate planning", 
    'fparea_insur_ds': "Insurance planning", 
    'fparea_invest_ds': "Investment planning", 
    'fparea_privbank_ds': "Private banking", 
    'fparea_respinvest_ds': "Responsible investing", 
    'fparea_retplan_ds': "Retirement planning", 
    'fparea_smallbus_ds': "Small business planning", 
    'fparea_succplan_ds': "Succession planning", 
    'fparea_taxplan_ds': "Tax planning" 
}

## value_labels are for UNIQUE value labels 
value_labels = {
    'sample': {0: 'FP', 1: 'IQPF'},
    'language': {9: 'English', 3084: 'French'},
    'gender': {
        1: 'Man', 
        2: 'Woman', 
        3: 'Prefer to self describe', 
        8888888: 'Prefer not to say'
        },
    'province': {
        1: 'British Columbia',
        2: 'Alberta',
        3: 'Saskatchewan',
        4: 'Manitoba',
        5: 'Ontario',
        6: 'Quebec',
        7: 'New Brunswick',
        8: 'Nova Scotia',
        9: 'Prince Edward Island',
        10: 'Newfoundland and Labrador',
        11: 'Northwest Territories',
        12: 'Nunavut',
        13: 'Yukon',
        14: 'None of the above'
    },
    'educ': {
    1: 'Less than high school diploma or its equivalent',
	 	2: 'High school diploma or a high school equivalency certificate',
	 	3: 'Trade certificate or diploma',
	 	4: 'College, CEGEP or other non-university certificate or diploma (other than trades certificates or diplomas)',
	 	5: 'University certificate or diploma below the bachelor\'s level',
	 	6: 'Bachelor\'s degree (e.g. B.A., B.Sc., LL.B.)',
	 	7: 'University certificate, diploma, degree above the bachelor\'s level'
     },
    'marital_status': {
		1:	'Married',
		2:	'Living common-law',
		3:	'Widowed',
		4:	'Separated',
		5:	'Divorced',
		6:	'Single, never married' 
    },
    'employment': {
		1:	'Accounting Firm',
		2:	'Credit Union',
		3:	'Financial Planning Firm',
		4:	'Insurance Company',
		5:	'Bank',
		6:	'Educational Institution',
		7:	'Investment / Mutual Fund Company',
		8:	'Managing General Agency (MGA)',
		9:	'Self-employed',
		10:	'Currently not working',
		11:	'Other',
		7777777: 'Don\'t know',
		8888888: 'Prefer not to say'
    },
    'service': {
    1:	'Advice on insurance',
		2:	'Advice on investments',
		3:	'Fin. plan. (without implementation)',
		4:	'Fin. plan. including implementation (sales)',
		7777777:	'Don\'t know',
		8888888:	'Prefer not to say' 
    },
    'compensation': {
		1:	'Salary only',
		2:	'Salary plus bonus based on sales',
		3:	'Primarily commissions',
		4:	'Primarily Assets under Management',
		5:	'Primarily fee for advice',
		6:	'Other' 
    },
    'refer': {
		1:	'Frequently',
		2:	'Occasionally',
		3:	'Rarely',
		4:	'Very Rarely',
		5:	'Never',
		7777777:	'Don\'t know',
		8888888:	'Prefer not to say' 
    },
    'patience': {
		1:	'Very patient',
		2:	'Patient',
		3:	'Impatient',
		4:	'Very impatient',
		7777777:	'Don\'t know',
		8888888:	'Prefer not to say' 
    },
    'risk': {
		1:	'Substantial fin risks for substantial returns',
		2:	'Above average fin risks for above-average returns',
		3:	'Average fin risks for average returns',
		4:	'Below average fin risks for below-average returns',
		5:	'No risk for small but certain return'
    },
    'stockmkt_confidence': {
		1:	'Extremely confident',
		2:	'Very confident',
		3:	'Somewhat confident',
		4:	'Not very confident',
		5:	'Not at all confident',
		7777777:	'Don\'t know',
		8888888:	'Prefer not to say' 
    },
    'selfass': {
		1:	'It is better than average',
		2:	'It is about the same',
		3:	'It is worse than the average',
		7777777:	'Don\'t know',
		8888888:	'Prefer not to say' 
    },
    'selfconf': {
		1:	'Yes, very much',
		2:	'Yes, I have some confidence',
		3:	'No, I have no confidence at all',
		7777777:	'Don\'t know',
		8888888:	'Prefer not to say' 
    }
}

## Value Labels that will be used many times
yesnodk = {
    0: 'no',
    1: 'yes',
    7777777: 'D/k',
    8888888: 'pnts',
    9999999:  'D/k pnts'
} 

yesnodk2 = {
    1: 'yes',
    2: 'no',
    7777777: 'D/k',
    8888888: 'pnts',
    9999999:  'D/k pnts'
} 

agreement = {
    0:	'Don\'t know',
		1:	'Disagree strongly',
		2:	'Disagree moderately',
		3:	'Disagree a little',
		4:	'Neither agree nor disagree',
		5:	'Agree a little',
		6:	'Agree moderately',
		7:	'Agree strongly'
}

agreement5 = {
    1:	'Don\'t know',
    2:	'Strongly Disagree',
		3:	'Disagree',
		4:	'Agree',
    5:	'Strongly Agree'    	
}

share = { 2: "zero", 3: "a quarter", 4: "half", 5: "almost all" }

value_labels_scn = {
    #Scenario 1
    'name1': {
    1: "James", 2: "Peter", 3: "Sally", 4: "Monica"     
    },
    'apr1': {
    1: "2.5%", 2: "5%", 3: "7.5%"     
    },
    'mtr1': {
    1: "30%", 2: "50%"    
    },
    'solicit1': {
    0: "No prompt", 1: "UL prompt"   
    },
    'answer1': {
    1: "RRSP", 2: "TFSA", 3: "UL", 4: "Repay debt"     
    },
    #Scenario 2
    'name2': {
    1: "John", 2: "Paul", 3: "Suzie", 4: "Mary"     
    },
		'bequest2': {
    1: "alone and has no children", 2: "with his/her partner who is 10 years younger"
    },
		'rate2': {
    1: "4%", 2: "6%", 3: "10%"
    },
		'health2': {
    1: "excellent (above average)", 2: "good (average)", 3: "poor (below average)"
    },  
		'solicit2': {
    0: "No prompt", 1: "Mutual Funds prompt"
    },
		'payout2': {
    1: "15,750", 2: "14,000"
    },
		'comp2': {
    0: "No prompt", 1: "Investment sale contributes to comp"
    },
		'answer2': {
    1: "Diversified MF with RATE and COMP",
		2: "Partial $10,000 life annuity with payout NAME (151,975.68 or 163,265.31)",
		3: "Seg funds with PAYOUT", 
    4: "All life annuity with payout NAME (23,030.00 or 21,437.50)"
    },
    #Scenario 3
    'name3': {
    1: "Joe", 2: "Justin", 3: "Sophie", 4: "Isabelle"   
    },
    'borrow3': {
    1: "1.5%", 2: "2.5%", 3: "3.5%"
    },
    'health3': {
    1: "excellent (above average)", 2: "good (average)", 3: "poor (below average)"  
    },
    'rate3': {
    1: "2%", 2: "3%", 3: "5%"
    },  
    'solicit3': {
    0: "No prompt", 1: "Mortgage prompt"
    },
    'answer3': {
    1: "Payoff mortgage", 
    2: "Invest in funds at expected RATE", 
    3: "LTCI at cost NAME (280 or 210)"
    },
    #Scenario 4
    'name4': {
    1: "Mike", 2: "Greg", 3: "Linda", 4: "Kate"  
    },
    'mutfees4': {
    1: "1%", 2: "2%", 3: "3%"
    },
    'segfees4': {
    1: "2%", 2: "3%", 3: "4%"   
    },
    'solicit4': {
    0: "No prompt", 1: "ETF prompt"
    },
    'answer4': {
    1: "Index-Linked GIC",
    2: "Mutual Fund of MUTFEES",
    3: "Seg. Funds of SEGFEES",
    4: "ETF"
    }    
}